### ISSUE TITLE
How to access imwrite?

### ISSUE THREAD

**Issue by Saumya-Gupta-26** [cgohlke/netpbmfile#2]
I get the following error : 
`   File "numpy2netpbm.py", line 14, in <module>
    netpbmfile.imwrite(os.path.join(ddir, dstname), nparr)
AttributeError: 'module' object has no attribute 'imwrite'`

My code snippet is:
import numpy as np 
import os
import netpbmfile

ddir = "/abc/"
srcname = "likelihood.npy"
dstname = "likelihood.pgm"

base = 65535.
nparr = np.clip((np.load(os.path.join(ddir,srcname))*base), 0., base).astype(np.uint16)
netpbmfile.imwrite(os.path.join(ddir, dstname), nparr)

Am I doing something wrong?

**Comment by Saumya-Gupta-26** [comment]
Looks like it's supposed to be `imsave` instead of `imwrite` . Please update the `README` to reflect this, thank you.

**Comment by cgohlke** [comment]
Both, `imsave` and `imwrite`, are working in the current version: https://github.com/cgohlke/netpbmfile/blob/6e3b9306d0d23ffd67149ddfea06621466e46944/netpbmfile/netpbmfile.py#L211-L223
